# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.cache/wt [current_project]
set_property parent.project_path C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/benchmark/5.sort/board/sort_board_data.coe
add_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/benchmark/5.sort/board/sort_board_inst.coe
add_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/benchmark/1.mem/mem_inst.coe
add_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/benchmark/1.mem/mem_data.coe
add_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/benchmark/2.i-type/i-type_inst.coe
add_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/benchmark/3.r-type/r-type_inst.coe
add_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/benchmark/4.branch/branch_inst.coe
read_verilog -library xil_defaultlib -sv {
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/defines.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/MiniMIPS32_SYS.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/imports/MiniMIPS32/MiniMIPS32.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/sign_extend_32.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/reg_file_32.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/mux_2.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/alu.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/rca.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/fulladder.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/control_unit.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/PC_trigger.sv
  C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/new/big2little.sv
}
read_ip -quiet C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all c:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/inst_rom/inst_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/inst_rom/inst_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files C:/Users/v25bh/Desktop/Lab5/MiniMIPS32_stu/MiniMIPS32/MiniMIPS32.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MiniMIPS32_SYS -part xc7a35tftg256-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MiniMIPS32_SYS.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MiniMIPS32_SYS_utilization_synth.rpt -pb MiniMIPS32_SYS_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
